# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1ca007a7b456a0d2629e162e175aebc3f4a7aebe84aa430d8a12f16a6d7f599b31c6005ff0147a276804d2f674f63c0a0b289bda3932f3b2fe1553b15133396

test:
  secret_key_base: c77ae0ea9b8a109a61eaaddba08540ea6de7baef9183ce76240c9906ee29867c9e75a7dca499721c65560d8856da0e4e5ebd3d7ebdb6fbaa8fddb76a2902c85d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
